vim lamp.yml
---
version: '3.0'

services:
 mydb:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: temp

 apache:
  image: httpd
  ports:
   - 8989:80
  links:
   - mydb:mysql

 php:
  image: php:7.2-apache
  links:
   - mydb:mysql
   - apache:httpd
...

To create containers from the above file
docker-compose -f lamp.yml up -d

To delete the containers
docker-compose -f lamp.yml down
